"""add message model

Revision ID: 9214e5cb348d
Revises: c14a9d8a9a62
Create Date: 2023-09-08 23:48:52.148602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9214e5cb348d'
down_revision: Union[str, None] = 'c14a9d8a9a62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender', sa.UUID(), nullable=False),
    sa.Column('receiver', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('time_seen', sa.DateTime(), nullable=True),
    sa.Column('time_delivered', sa.DateTime(), nullable=False),
    sa.Column('is_delivered', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['receiver'], ['user.uuid'], ),
    sa.ForeignKeyConstraint(['sender'], ['user.uuid'], ),
    sa.PrimaryKeyConstraint('id', 'sender', 'receiver'),
    sa.UniqueConstraint('sender', 'receiver', name='unique_user_constraint')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    # ### end Alembic commands ###
